name: freelec-springboot2-webservice

on:
  push:
    branches:
      - master # (1) 실습하시는분들은 master로 하시면 됩니다. (저는 별도 브랜치로 지정)
  workflow_dispatch: # (2) 수동 실행

permissions:
    id-token: write
    contents: read
jobs:
  build:
    runs-on: ubuntu-latest # (3)

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # (4)
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: arn:aws:iam::349955768468:role/asc6
            role-session-name: samplerolesession
            aws-region: "ap-northeast-2"
            
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1 # (5)
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # (6)
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build # (7)
        shell: bash
        
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        application_name: asc6
        environment_name: Asc6-env
        
        region: ap-northeast-2
